# Generated by Django 3.2.14 on 2022-08-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsbase', '0002_learning_material_student_learning_task_student_whiteboard_student_zoom_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='learning_intention_student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('learning_intention', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
