# Generated by Django 3.2.14 on 2022-08-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsbase', '0004_rename_learning_intention_student_learning_intention_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learning_intention_teacher',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
