# Generated by Django 3.2.14 on 2022-08-08 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lsbase', '0007_auto_20220808_0213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learning_intentions_student',
            old_name='reponse',
            new_name='response',
        ),
    ]
