# Generated by Django 3.2.14 on 2022-08-08 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lsbase', '0010_rename_learning_intention_teacher_learning_intention_teach'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='learning_intention_teach',
            new_name='learning_intention_teacher',
        ),
    ]
