# Generated by Django 3.2.14 on 2022-08-08 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lsbase', '0011_rename_learning_intention_teach_learning_intention_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='learning_intention_teacher',
            new_name='learning_intentions',
        ),
    ]
