# Generated by Django 3.2.14 on 2022-08-08 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lsbase', '0012_rename_learning_intention_teacher_learning_intentions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='learning_intentions',
            new_name='learning_intention',
        ),
        migrations.RenameField(
            model_name='learning_intention',
            old_name='learning_intention',
            new_name='li',
        ),
    ]
