# Generated by Django 3.2.14 on 2022-08-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsbase', '0013_auto_20220808_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learning_intention',
            name='li',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
