# Generated by Django 3.2.14 on 2022-08-08 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lsbase', '0014_alter_learning_intention_li'),
    ]

    operations = [
        migrations.DeleteModel(
            name='learning_intentions_student',
        ),
        migrations.RemoveField(
            model_name='learning_material_student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='learning_task_student',
            name='user',
        ),
        migrations.DeleteModel(
            name='whiteboard_student',
        ),
        migrations.DeleteModel(
            name='zoom_student',
        ),
        migrations.DeleteModel(
            name='learning_material_student',
        ),
        migrations.DeleteModel(
            name='learning_task_student',
        ),
    ]
