# Generated by Django 3.2.14 on 2022-08-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsbase', '0016_alter_learning_intention_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learning_intention',
            name='li',
            field=models.CharField(max_length=100),
        ),
    ]
