# Generated by Django 3.2.14 on 2022-08-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsbase', '0017_alter_learning_intention_li'),
    ]

    operations = [
        migrations.CreateModel(
            name='learning_task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lt', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
