# Generated by Django 3.2.14 on 2022-08-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsbase', '0018_learning_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='learning_intention',
            name='text',
            field=models.TextField(default='', max_length=100),
        ),
    ]
