# Generated by Django 3.2.14 on 2022-08-09 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lsbase', '0020_auto_20220808_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='learning_task',
            name='happy',
            field=models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='happy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('unselected', 'unseleted'), ('selected', 'selected')], default='selected', max_length=10)),
                ('learning_intention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lsbase.learning_intention')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
