# Generated by Django 3.2.14 on 2022-08-09 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lsbase', '0021_auto_20220809_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learning_task',
            name='happy',
        ),
        migrations.AddField(
            model_name='learning_intention',
            name='li_happy',
            field=models.ManyToManyField(blank=True, default=None, related_name='li_happy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learning_intention',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learning_intention',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='happy',
            name='value',
            field=models.CharField(choices=[('no', 'no'), ('yes', 'yes')], default='yes', max_length=10),
        ),
        migrations.AlterField(
            model_name='learning_intention',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='learning_intention',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='learning_intention',
            name='li',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='learning_task',
            name='lt',
            field=models.CharField(max_length=20),
        ),
    ]
