# Generated by Django 3.2.14 on 2022-08-10 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lsbase', '0028_auto_20220810_0309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Happy_Select',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Select', 'Select'), ('Unselect', 'Unselect')], default='Select', max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='liked',
            new_name='happy',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.AlterField(
            model_name='happy',
            name='value',
            field=models.CharField(choices=[('no', 'no'), ('yes', 'yes')], default='yes', max_length=10),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.AddField(
            model_name='happy_select',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lsbase.post'),
        ),
        migrations.AddField(
            model_name='happy_select',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
