# Generated by Django 3.2.14 on 2022-08-10 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lsbase', '0029_auto_20220810_0431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='happy',
            name='learning_intention',
        ),
        migrations.RemoveField(
            model_name='happy',
            name='user',
        ),
        migrations.DeleteModel(
            name='learning_task',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='happy',
        ),
        migrations.RemoveField(
            model_name='learning_intention',
            name='li',
        ),
        migrations.RemoveField(
            model_name='learning_intention',
            name='li_happy',
        ),
        migrations.RemoveField(
            model_name='learning_intention',
            name='student',
        ),
        migrations.AddField(
            model_name='learning_intention',
            name='author',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learning_intention',
            name='happy',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learning_intention',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='happy_select',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lsbase.learning_intention'),
        ),
        migrations.DeleteModel(
            name='happy',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
