# Generated by Django 3.2.14 on 2022-08-10 05:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lsbase', '0036_alter_learning_intention_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='happy_select',
            old_name='post',
            new_name='learning_intention',
        ),
        migrations.AlterField(
            model_name='learning_intention',
            name='happy',
            field=models.ManyToManyField(blank=True, default=None, related_name='happy_selected', to=settings.AUTH_USER_MODEL),
        ),
    ]
