# Generated by Django 3.2.14 on 2022-08-15 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lsbase', '0042_auto_20220810_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learning_Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=150)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ltauthor', to=settings.AUTH_USER_MODEL)),
                ('complete', models.ManyToManyField(blank=True, default=None, related_name='complete', to=settings.AUTH_USER_MODEL)),
                ('inprogress', models.ManyToManyField(blank=True, default=None, related_name='inprogress', to=settings.AUTH_USER_MODEL)),
                ('needhelp', models.ManyToManyField(blank=True, default=None, related_name='needhelp', to=settings.AUTH_USER_MODEL)),
                ('notstarted', models.ManyToManyField(blank=True, default=None, related_name='notstarted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LTNotStarted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Select', 'Select'), ('Unselect', 'Unselect')], default='Select', max_length=10)),
                ('learning_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lsbase.learning_task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LTNeedHelp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Select', 'Select'), ('Unselect', 'Unselect')], default='Select', max_length=10)),
                ('learning_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lsbase.learning_task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LTInProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Select', 'Select'), ('Unselect', 'Unselect')], default='Select', max_length=10)),
                ('learning_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lsbase.learning_task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LTComplete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Select', 'Select'), ('Unselect', 'Unselect')], default='Select', max_length=10)),
                ('learning_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lsbase.learning_task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
