# Generated by Django 3.2.14 on 2022-08-15 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lsbase', '0043_learning_task_ltcomplete_ltinprogress_ltneedhelp_ltnotstarted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learning_task',
            old_name='title',
            new_name='lttitle',
        ),
    ]
