# Generated by Django 3.2.14 on 2022-08-15 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lsbase', '0044_rename_title_learning_task_lttitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learning_task',
            old_name='lttitle',
            new_name='title',
        ),
    ]
