# Generated by Django 3.2.14 on 2022-09-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsbase', '0045_rename_lttitle_learning_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learning_intention',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
