# Generated by Django 3.2.14 on 2022-09-04 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lsbase', '0055_auto_20220904_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learning_intention',
            old_name='lititle',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='learning_task',
            old_name='lttitle',
            new_name='title',
        ),
    ]
